# Exported from Render on 2025-07-03T17:48:34Z
services:
  - type: web
    name: 5-Guys-University-Backend
    runtime: python
    repo: https://github.com/Shawaiz99/5-Guys-University-Backend
    plan: free
    envVars:
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ADMIN_SWATCH
        sync: false
      - key: FLASK_APP
        sync: false
      - key: FLASK_ENV
        sync: false
    region: virginia
    buildCommand: bash pip install pipenv && pipenv install --system --deploy
    startCommand: gunicorn wsgi:app --workers 3 --timeout 60
    autoDeployTrigger: "off"
version: "1"
